services:
  - type: web
    name: smart-health-api
    env: go
    region: oregon
    plan: free
    buildCommand: go build -o server main.go
    startCommand: ./server
    healthCheckPath: /health
    envVars:
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: PORT
        value: 10000
